export default{
    PRIMARY_COLOR: "#C2A77A", //Grown
    PRIMARY_COLOR_DARK: "#357443",
    PRIMARY_COLOR_LIGHT: "#61DF7D", 

    SECONDARY_COLOR:"#fff", //White
    SECONDARY_COLOR_DARK: "#C7C7C7",

    NAV_BAR_BACK:'271d14',
    INACTIVE_ICON:'#ada7a3',

    TERTIARY_COLOR:"#000", //Black
    TERTIARY_COLOR_LIGHT: "#4E4E4E",
    
    QUATERNARY_COLOR:"#271D14", // Dark Brown

    QUINARY_COLOR: "#C88D63",

    NAV_BAR_ICON:"#e5d3b3"
    
};